### ISSUE TITLE
Bundle failed with ruby 2.4.1

### ISSUE THREAD

**Issue by foi** [crystal-lang/omnibus-crystal#23]
**I think it's because Ruby 2.4 unifies Fixnum and Bignum into Integer**

-------------------------------------------------------------------------------------------------------------------------------
```
[foi@foi-pc omnibus-crystal]$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[foi@foi-pc omnibus-crystal]$ bundle
The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run gem install bundler --pre
The git source git://github.com/opscode/omnibus-software.git uses the git protocol, which transmits data without encryption. Disable this warning with bundle config git.allow_insecure true, or switch to the https protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Using bundler 1.15.4
Using chef-sugar 2.3.0
Using cleanroom 1.0.0
Using ffi 1.9.5
Using libyajl2 1.0.1
Using ipaddress 0.8.0
Using mime-types 1.25.1
Using mixlib-cli 1.5.0
Using mixlib-config 2.1.0
Using mixlib-log 1.6.0
Using mixlib-shellout 1.4.0
Using systemu 2.6.4
Using wmi-lite 1.0.0
Using thor 0.19.1
Using omnibus-software 4.0.0 from git://github.com/opscode/omnibus-software.git (at master@ff7d627)
Fetching ffi-yajl 1.1.0
Installing ffi-yajl 1.1.0 with native extensions
Using uber-s3 0.2.4
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ffi-yajl-1.1.0/ext/ffi_yajl/ext/encoder
/usr/local/rbenv/versions/2.4.1/bin/ruby -r ./siteconf20171004-14521-xdy9k0.rb extconf.rb
 -I/usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include $(cflags)
 -L/usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib -L. -L/usr/local/rbenv/versions/2.4.1/lib  -fstack-protector -rdynamic -Wl,-export-dynamic
checking for yajl/yajl_tree.h... yes
creating Makefile

current directory: /usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ffi-yajl-1.1.0/ext/ffi_yajl/ext/encoder
make "DESTDIR=" clean

current directory: /usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ffi-yajl-1.1.0/ext/ffi_yajl/ext/encoder
make "DESTDIR="
compiling encoder.c
encoder.c: In function ‘Init_encoder’:
encoder.c:304:20: error: ‘rb_cFixnum’ undeclared (first use in this function); did you mean ‘rb_isalnum’?
   rb_define_method(rb_cFixnum, "ffi_yajl", rb_cFixnum_ffi_yajl, 2);
                    ^~~~~~~~~~
                    rb_isalnum
encoder.c:304:20: note: each undeclared identifier is reported only once for each function it appears in
encoder.c:305:20: error: ‘rb_cBignum’ undeclared (first use in this function); did you mean ‘rb_cFixnum’?
   rb_define_method(rb_cBignum, "ffi_yajl", rb_cBignum_ffi_yajl, 2);
                    ^~~~~~~~~~
                    rb_cFixnum
encoder.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
make: *** [Makefile:242: encoder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ffi-yajl-1.1.0 for inspection.
Results logged to /usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/ffi-yajl-1.1.0/gem_make.out

An error occurred while installing ffi-yajl (1.1.0), and Bundler cannot continue.
Make sure that gem install ffi-yajl -v '1.1.0' succeeds before bundling.

In Gemfile:
  omnibus was resolved to 4.0.0.rc.1, which depends on
    ohai was resolved to 7.4.0, which depends on
      ffi-yajl
```

**Comment by mverzilli** [comment]
We just merged to master a version which should work with Ruby 2.4. I'll assume that fixes your issue and close it, but feel free to reopen if you still see it.
